markdown: rdiscount
permalink: /:title/
url: http://github.thinkingbar.com
name: 飘过的小牛
author: niushuai
qq: 389346114
email: hnns1990@gmail.com
duoshuo: niushuai
weibo: 1891858481
hub: niushuai
pygments: true
safe: true
paginate: 20
about: "弱菜一枚。"
